server: utils.cpp webserver.cpp
	g++ utils.cpp webserver.cpp -o server

client: utils.cpp client.cpp
	g++ utils.cpp client.cpp -o client

server_03 : utils.cpp ./day03/webserver.cpp
	g++  utils.cpp ./day03/webserver.cpp -o ./day03/server_03